spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret:
    key: ${JWT_SECRET_KEY:${JWT_SECRET_KEY}==}
